### ISSUE TITLE
name '_np' is not defined on Python 3.7

### ISSUE THREAD

**Issue by eyp** [classner/pymp#13]
I'm trying to execute one of the tests on Python 3.7, but anything I do I always get the same error:

**The program:**

import pymp
pymp.config.nested = False
pymp.config.thread_limit = 4
tlist = pymp.shared.list()
with pymp.Parallel(2) as p:
  for _ in p.range(1000):
    tlist.append(1.)

**The error:**

python3 test_pymp
Traceback (most recent call last):
  File "test_pymp", line 1, in <module>
    import pymp
  File "/Users/edu/Library/Python/3.7/lib/python/site-packages/pymp/__init__.py", line 14, in <module>
    import pymp.shared as _shared
  File "/Users/edu/Library/Python/3.7/lib/python/site-packages/pymp/shared.py", line 21, in <module>
    def array(shape, dtype=_np.float64, autolock=False):
NameError: name '_np' is not defined

**Comment by eyp** [comment]
Ok, forget it, after looking at the source code I realized I was missing numpy in my virtual environment.
