### ISSUE TITLE
Having issue with OpenMP attributes

### ISSUE THREAD

**Issue by Volpone24** [classner/pymp#18]
I installed pymp using pip but I cannot use the functions.

I am using Python 3.8 and using the idle

Traceback (most recent call last):
  File "C:\Users\RISHAB\Desktop\pdcp.py", line 18, in <module>
    padded = pymp.shared.array((l+2,b+2), dtype='uint8')
AttributeError: module 'pymp' has no attribute 'shared'

Traceback (most recent call last):
  File "C:\Users\RISHAB\Desktop\pdcp.py", line 10, in <module>
    pymp.config.nested = True
AttributeError: module 'pymp' has no attribute 'config'

**Comment by classner** [comment]
Hi @Volpone24 !

Unfortunately, pymp does not work on Windows (I am assuming you are running on Windows due to the file name mentioned in your post). It should raise an Exception stating that, please let me know if it does not. Running in WSL/WSL2 will probably work. Can you confirm that you're on a supported platform?

**Comment by Aparajit-Garg** [comment]
Hi @classner, amazing repo. I am trying out your code on ubuntu 18.04 on pycharm using python3.6. I'm getting the same error. I'm attaching the stack trace:

2021-09-22 18:00:28,502 __main__ INFO Predicting the 3D body on `testing/33.png` (saving to `testing/33.png_body_directseparate.pkl`).
Traceback (most recent call last):
  File "direct3d/bodyfit.py", line 607, in <module>
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/msi/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/msi/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/msi/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msi/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "direct3d/bodyfit.py", line 582, in cli
    do_degrees=[0.])
  File "direct3d/bodyfit.py", line 381, in run_single_fit
    _pymp.shared.array(j2d.shape, dtype='float32'),
AttributeError: module 'pymp' has no attribute 'shared'

**Comment by classner** [comment]
I assume you manually tried to install it with ‘pip install pymp’ - this is the wrong package! You need to uninstall it first, then install ‘pip install pymp-pypi’.
