### ISSUE TITLE
  if __name__ == '__main__':                 freeze_support()

### ISSUE THREAD

**Issue by Marie0909** [classner/pymp#27]
if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

when I use it, I got a error like this. However, I actually add " if __name__ == '__main__': " in my code! Therefore, current available solutions for this error does not work for me. If I don't use pymp, this error will dispear. Therefore, I guess pymp is the reason. Could you kindly let me know the solution for this?

Thanks in advance,
Lei

**Comment by Marie0909** [comment]
Just notice "the package will only work on systems with fork support (sorry, not on Windows)."! Maybe this is the reason why I can't use it in my PC?

**Comment by classner** [comment]
Hi @Marie0909 ,

I lack the context to give you a more detailed response. However, pymp indeed does not work on Windows, so if you are trying that this might explain the situation. Please let me know if that is the issue.

Christoph

**Comment by susannasiebert** [comment]
I'm running into the same issue. This is in a python 3.8.12 conda environment on MacOS:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/bin/pvacseq", line 5, in <module>
    from pvactools.tools.pvacseq.main import main
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/tools/pvacseq/__init__.py", line 18, in <module>
    from . import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 7, in <module>
    from pvactools.lib.prediction_class import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/__init__.py", line 22, in <module>
    from . import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 9, in <module>
    from pvactools.lib.calculate_reference_proteome_similarity import CalculateReferenceProteomeSimilarity
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 17, in <module>
    import pymp
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pymp/__init__.py", line 14, in <module>
    import pymp.shared as _shared
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pymp/shared.py", line 15, in <module>
    _MANAGER = _multiprocessing.Manager()  # pylint: disable=no-member
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/ssiebert/opt/miniconda3/envs/py38/bin/pvacseq", line 5, in <module>
    from pvactools.tools.pvacseq.main import main
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/tools/pvacseq/__init__.py", line 18, in <module>
    from . import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 7, in <module>
    from pvactools.lib.prediction_class import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/__init__.py", line 22, in <module>
    from . import *
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/post_processor.py", line 9, in <module>
    from pvactools.lib.calculate_reference_proteome_similarity import CalculateReferenceProteomeSimilarity
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pvactools/lib/calculate_reference_proteome_similarity.py", line 17, in <module>
    import pymp
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pymp/__init__.py", line 14, in <module>
    import pymp.shared as _shared
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/site-packages/pymp/shared.py", line 15, in <module>
    _MANAGER = _multiprocessing.Manager()  # pylint: disable=no-member
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/ssiebert/opt/miniconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by susannasiebert** [comment]
I can confirm that the 0.5.0 version on master fixes this issue. Thank for the quick bugfix!
